/*
  The intrinsic pixel size of every photo and screenshot in the site's content.

  Why this exists: `<Image>` needs `width` and `height` to reserve the right box
  before a picture arrives, and the panel bodies were passing one hardcoded
  guess (880x550) for every image in the site. The guess is not used for the
  final shape - the width/height attributes map to `aspect-ratio: auto W / H`,
  and `auto` defers to the real ratio once the file loads - so nothing looked
  stretched and the bug was invisible on a fast connection.

  What it did instead was reserve the WRONG box. Measured on a throttled
  connection, a hackathon panel opened with its "Impact" heading 753px below
  where it ended up: six images each holding a 355px slot, then collapsing to
  their true heights (91px for a wide chart, 385px for a squarer one) and
  dragging the whole page up under the reader's eye.

  Next can read these numbers itself from a static `import`, but only for a
  static import - content here carries `src` as a string so that one entry can
  be pointed at a new file by editing one line. So the sizes are measured and
  written down, and imageSizes.test.ts re-reads every file's header and fails
  if the table has drifted. Sizes change when a file is replaced, which is
  exactly when nobody thinks to look here.

  Generated by reading the PNG IHDR / JPEG SOF headers of everything under
  public/{about,projects,hackathons}.
*/
export const IMAGE_SIZES: Record<string, readonly [number, number]> = {
  "/about/brainhack.jpg": [1280, 960],
  "/about/portrait.jpg": [960, 1280],
  "/about/presentation.jpg": [1280, 853],
  "/hackathons/brainhack-code-exp-2026/final-showcase.jpg": [2880, 2160],
  "/hackathons/brainhack-code-exp-2026/infographic.png": [853, 1280],
  "/hackathons/brainhack-code-exp-2026/logo.png": [1254, 1254],
  "/hackathons/brainhack-code-exp-2026/podium.jpg": [2880, 2160],
  "/hackathons/brainhack-code-exp-2026/showcase.jpg": [2880, 2160],
  "/hackathons/maritime-one-case-summit-2026/map.png": [2222, 1118],
  "/hackathons/maritime-one-case-summit-2026/route-optimisation.png": [1318, 1248],
  "/hackathons/maritime-one-case-summit-2026/supplier-analysis.png": [1296, 1250],
  "/hackathons/naisc-2026-singtel-churn/drift-detection-summary.png": [952, 329],
  "/hackathons/naisc-2026-singtel-churn/feature-importance-cbdt.png": [2384, 377],
  "/hackathons/naisc-2026-singtel-churn/model-performance-metrics.png": [208, 141],
  "/hackathons/naisc-2026-singtel-churn/psi-by-drift-type.png": [1197, 295],
  "/hackathons/naisc-2026-singtel-churn/psi-per-feature.png": [1593, 591],
  "/hackathons/naisc-2026-singtel-churn/psi-severity-table.png": [785, 485],
  "/hackathons/nus-maritime-hackathon-2026/cost-efficiency.png": [1155, 316],
  "/hackathons/nus-maritime-hackathon-2026/cost.png": [1155, 316],
  "/hackathons/nus-maritime-hackathon-2026/distribution-main-engine.png": [574, 316],
  "/hackathons/nus-maritime-hackathon-2026/distribution-safety.png": [574, 316],
  "/hackathons/nus-maritime-hackathon-2026/map.png": [1155, 640],
  "/projects/git-dummy/commit-graph.png": [1992, 1242],
  "/projects/git-dummy/guided-tour.png": [1986, 1242],
  "/projects/git-dummy/logo-card.png": [1600, 1000],
  "/projects/git-dummy/logo.png": [500, 500],
  "/projects/git-dummy/sign-in.png": [1994, 1244],
  "/projects/git-dummy/track-a-project.png": [1994, 1296],
  "/projects/millitary-stores-telegram-bot/bot.png": [450, 423],
  "/projects/millitary-stores-telegram-bot/overview.png": [1108, 537],
  "/projects/millitary-stores-telegram-bot/reporting.png": [474, 340],
};

/**
 * The box to reserve for `src`, in intrinsic pixels.
 *
 * Falls back to a 16:10 landscape for an image with no entry, which is the
 * shape most screenshots here are. A wrong box is a jump; no box at all is a
 * bigger one, so the fallback is deliberately not `undefined`.
 */
export function sizeOf(src: string): { width: number; height: number } {
  const found = IMAGE_SIZES[src];
  if (!found) return { width: 1600, height: 1000 };
  return { width: found[0], height: found[1] };
}
